// Gigs.js

// Define the gigs data as an array of objects
const gigsData = [
    {
        id: "1",
        companyLogo: "https://www.openzeppelin.com/hubfs/iso-openzeppelin.svg",
        jobTitle: "Web3.js Developer",
        companyName: "Amazon",
        duration: "3+ months",
        rate: "$260/Day",
        type: "Full time",
        category: "Development",
    },
    {
        id: "2",
        companyLogo: "https://www.openzeppelin.com/hubfs/iso-openzeppelin.svg",
        jobTitle: "Smart Contract Developer",
        companyName: "Google",
        duration: "3-6 months",
        rate: "$250/Day",
        type: "Part time",
        category: "Blockchain",
    },
    {
        id: "3",
        companyLogo: "https://www.openzeppelin.com/hubfs/iso-openzeppelin.svg",
        jobTitle: "Blockchain Engineer",
        companyName: "Facebook",
        duration: "1-3 months",
        rate: "$200/Day",
        type: "Contract",
        category: "Development",
    },
    {
        id: "4",
        companyLogo: "https://www.openzeppelin.com/hubfs/iso-openzeppelin.svg",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "5",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNexcDQElBSuSktOrWNuyxb2gV6qHvO01s1w&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "6",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNexcDQElBSuSktOrWNuyxb2gV6qHvO01s1w&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "7",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNexcDQElBSuSktOrWNuyxb2gV6qHvO01s1w&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "8",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNexcDQElBSuSktOrWNuyxb2gV6qHvO01s1w&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "9",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShwtR_AaGBkWKpbkJoNjzgqkvFcjYdviD0cw&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "10",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShwtR_AaGBkWKpbkJoNjzgqkvFcjYdviD0cw&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "11",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShwtR_AaGBkWKpbkJoNjzgqkvFcjYdviD0cw&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "12",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyejSxfv1VRb4-lAhpR2xyG-_-A1XH0n9riw&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "13",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyejSxfv1VRb4-lAhpR2xyG-_-A1XH0n9riw&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "14",
        companyLogo: "https://docs.aboutcircles.com/~gitbook/image?url=https%3A%2F%2F2619591868-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252Fs76GmMOXUUWWi7YK8Ugp%252Ficon%252FGGds8ADQ4BUloNFDKNWw%252Fcircles%2520logo-icon-color.png%3Falt%3Dmedia%26token%3D79fa906c-3f0a-4299-ad68-ff84e735e519&width=32&dpr=2&quality=100&sign=bb110d38&sv=1",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "15",
        companyLogo: "https://docs.aboutcircles.com/~gitbook/image?url=https%3A%2F%2F2619591868-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252Fs76GmMOXUUWWi7YK8Ugp%252Ficon%252FGGds8ADQ4BUloNFDKNWw%252Fcircles%2520logo-icon-color.png%3Falt%3Dmedia%26token%3D79fa906c-3f0a-4299-ad68-ff84e735e519&width=32&dpr=2&quality=100&sign=bb110d38&sv=1",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "16",
        companyLogo: "https://docs.aboutcircles.com/~gitbook/image?url=https%3A%2F%2F2619591868-files.gitbook.io%2F%7E%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252Fs76GmMOXUUWWi7YK8Ugp%252Ficon%252FGGds8ADQ4BUloNFDKNWw%252Fcircles%2520logo-icon-color.png%3Falt%3Dmedia%26token%3D79fa906c-3f0a-4299-ad68-ff84e735e519&width=32&dpr=2&quality=100&sign=bb110d38&sv=1",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "17",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMg4V_y3DnS8Jxh2_M5p0mBI0VHshDyRsRGQ&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "18",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMg4V_y3DnS8Jxh2_M5p0mBI0VHshDyRsRGQ&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "19",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMg4V_y3DnS8Jxh2_M5p0mBI0VHshDyRsRGQ&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
    {
        id: "20",
        companyLogo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMg4V_y3DnS8Jxh2_M5p0mBI0VHshDyRsRGQ&s",
        jobTitle: "Designer",
        companyName: "Celo",
        duration: "2-4 weeks",
        rate: "$150/Day",
        type: "Part-Time",
        category: "Ui/Ux",
    },
];

export default gigsData;
